### ISSUE TITLE
whole pipeline

### ISSUE THREAD

**Issue by chengaopro** [embodied-agent-interface/embodied-agent-interface#5]
great works!

I'm wondering is there a complete code pipeline from input to output? BTW, do all LLMs use the same input prompts generated by '--mode generate_prompts' for evaluation?

**Comment by bryanzhou008** [comment]
Thanks! Yes, all LLMs use the same input prompts generated by '--mode generate_prompts'. As for "a complete code pipeline", do you mean for evaluating your own model or for evaluating common existing models?

**Comment by bryanzhou008** [comment]
Got it, for evaluating common existing models,  we are currently working on integrating a one-click pipeline that only requires a user API key input to run batch evaluation of multiple  models. It uses the HELM Library (https://github.com/stanford-crfm/helm) as a sub-repo to do quick LLM inference.

For now, you may feel free to use either the official HELM repo (https://github.com/stanford-crfm/helm) or our adapted version (https://github.com/bryanzhou008/helm), which was used for running experiments in the paper.

**Comment by chengaopro** [comment]
sounds great, thx!
