### ISSUE TITLE
Is there a unified LLM Inference script?

### ISSUE THREAD

**Issue by Smith-xuan** [embodied-agent-interface/embodied-agent-interface#6]
Your work is very insightful and great! 

Based on experience, different inference engines and configurations may also have a impact on the performance of LLMs. If I want to evaluate my own model or open-source and commercial models not mentioned in the paper on EAI, could you provide a unified LLM inference script or inform me of the specific reasoning engine and configurations?

**Comment by bryanzhou008** [comment]
Thanks! Yes, we are currently we are currently working on integrating a one-click pipeline that only requires a user API key input to run batch evaluation of multiple models. It uses the HELM Library (https://github.com/stanford-crfm/helm) as a sub-repo to do quick LLM inference. Please stay tuned as it will be released soon.

For now, you may feel free to use either the official HELM repo (https://github.com/stanford-crfm/helm) or our adapted version (https://github.com/bryanzhou008/helm), which was used for running experiments in the paper. Both should be pretty easy to setup.

As for evaluating your own models which may be private and have parameters unknown to us, it is not possible for us to provide a universal script. Thus, please feel free to use/tune the best decoding configurations for your LLM and use our evaluation scripts to check its performance.

**Comment by jhpark98** [comment]
Hello @bryanzhou008 for the awesome work. I am wondering if there is any progress been made in "one-click pipeline." I spend some good time trying to figure out how to use helm to generate llm response using the generated prompts from your work. Would there be more specific guide on how to use helm to generate the outputs?
